In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

In [2]:
df=pd.read_csv(r"C:\Users\Dell\Documents\My ML Projects\Customer churn project\data\Telco_customer_churn.csv")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [3]:
df.shape

(7043, 33)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   str
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), str(24)
memory usage: 1.8 MB

In [5]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [6]:
df.columns=df.columns.str.strip()

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   str
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), str(24)
memory usage: 1.8 MB

In [8]:
cols_to_drop=['CustomerID','Zip Code','Latitude','Longitude','Lat Long','Churn Label','Churn Score','CLTV','Churn Reason']
df.drop(columns=[col for col in cols_to_drop if col in df.columns],inplace=True)

In [9]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')
df.isnull().sum()

Count                 0
Country               0
State                 0
City                  0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Tenure Months         0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Monthly Charges       0
Total Charges        11
Churn Value           0
dtype: int64

In [10]:
df.dropna(subset=['Total Charges'], inplace=True)

In [11]:
df['Churn Value'].head()

0    1
1    1
2    1
3    1
4    1
Name: Churn Value, dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Count              7032 non-null   int64
 1   Country            7032 non-null   str
 2   State              7032 non-null   str
 3   City               7032 non-null   str
 4   Gender             7032 non-null   str
 5   Senior Citizen     7032 non-null   str
 6   Partner            7032 non-null   str
 7   Dependents         7032 non-null   str
 8   Tenure Months      7032 non-null   int64
 9   Phone Service      7032 non-null   str
 10  Multiple Lines     7032 non-null   str
 11  Internet Service   7032 non-null   str
 12  Online Security    7032 non-null   str
 13  Online Backup      7032 non-null   str
 14  Device Protection  7032 non-null   str
 15  Tech Support       7032 non-null   str
 16  Streaming TV       7032 non-null   str
 17  Streaming Movies   7032 non-null   str
 18  Contract           7032 non-null   str
 19  Paperless Billing  7032 non-null   str
 20  Payment Method     7032 non-null   str
 21  Monthly Charges    7032 non-null   float64
 22  Total Charges      7032 non-null   float64
 23  Churn Value        7032 non-null   int64
dtypes: float64(2), int64(3), str(19)
memory usage: 1.3 MB

In [ ]:
df['Churn Value'].value_counts(normalize=True)

Churn Value
0    0.734215
1    0.265785
Name: proportion, dtype: float64

In [ ]:
df.groupby('Churn Value')['Tenure Months'].mean()

Churn Value
0    37.650010
1    17.979133
Name: Tenure Months, dtype: float64

customers who churned stayed only 18 months on average.

customers who stayed have been with company 38 months

**So newer customers are more likely to churn**

**From EDA, I observed that customers with lower tenure had significantly higher churn rates. The average tenure of churned customers was around 18 months compared to 38 months for retained customers. This idicates early stage churn risk.**


Based on this insight:
1. Improve onboarding experience
2. Offer discounts in first 6 to 12 months
3. Provide engagement programs for new users

In [15]:
df.groupby('Contract')['Churn Value'].mean()

Contract
Month-to-month    0.427097
One year          0.112772
Two year          0.028487
Name: Churn Value, dtype: float64

**Customers with month to month contracts had churn rate ~43 %,whereas two year contract customers had less than 3% churn.This suggests that contract commitment significantly reduces churn risk.**

Company can :
1. Offer discounts to move month-to-month customers to annual plans
2. Give incentives for long term contracts
3. Target month-to-month users with retention campaigns

In [16]:
df.groupby('Internet Service')['Churn Value'].mean()

Internet Service
DSL            0.189983
Fiber optic    0.418928
No             0.074342
Name: Churn Value, dtype: float64

**Customers using Fiber optic internet showed significantly higher churn(~42%)compared to DSL(~19%). This may indicate pricing sensitivity or service dissatisfaction among fiber users.**

In [15]:
#** Data Preprocessing**#

In [17]:
df.dtypes

Count                  int64
Country                  str
State                    str
City                     str
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges        float64
Churn Value            int64
dtype: object

**Separate Target and Features**

**Target=Churn Value**

In [27]:
x = df.drop([
    'Churn Value',
    'Count',
    'Country',
    'State',
    'City'
], axis=1)

y = df['Churn Value']

x_encoded = pd.get_dummies(x, drop_first=True)

x_encoded.shape

(7032, 30)

In [29]:
x.dtypes.value_counts()

str        16
float64     2
int64       1
Name: count, dtype: int64

In [30]:
categorical_cols=x.select_dtypes(include='object').columns
categorical_cols

C:\Users\Dell\AppData\Local\Temp\ipykernel_7788\2321429156.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols=x.select_dtypes(include='object').columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method'],
      dtype='str')

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [32]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [33]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8052594171997157
[[908 125]
 [149 225]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1033
           1       0.64      0.60      0.62       374

    accuracy                           0.81      1407
   macro avg       0.75      0.74      0.75      1407
weighted avg       0.80      0.81      0.80      1407